import os
import requests
import logging
import shutil
from fastapi import APIRouter, HTTPException, UploadFile, File
from pydantic import BaseModel
from dotenv import load_dotenv

from backend.document_loader import load_documents, split_text
from backend.vector_store import VectorStore

# Load environment variables
from pathlib import Path
env_path = Path(__file__).resolve().parent / ".env"
load_dotenv(dotenv_path=env_path)

LLAMA_API_KEY = os.getenv("LLAMA_API_KEY")
LLAMA_API_URL = os.getenv("LLAMA_API_URL", "https://api.groq.com/openai/v1/chat/completions")
LLAMA_MODEL = os.getenv("LLAMA_MODEL", "llama-3.1-8b-instant")

# Validate API Key
if not LLAMA_API_KEY:
    raise ValueError("Missing API key. Please set LLAMA_API_KEY in your .env file.")

router = APIRouter(prefix="/api", tags=["LLaMA API"])

# Pydantic request schema
class ChatRequest(BaseModel):
    message: str

# Initialize vector store
vector_store = VectorStore()

def initialize_vector_store():
    """Checks for existing vector store file and builds it from PDF if not found."""
    if not os.path.exists(vector_store.store_file):
        pdf_path = "backend/data/simple.pdf"
        if os.path.exists(pdf_path):
            logging.info(f"Vector store not found. Loading and indexing {pdf_path}...")
            try:
                text = load_documents(pdf_path)
                chunks = split_text(text)
                vector_store.add_vectors(chunks)
                logging.info(f"Successfully indexed {len(chunks)} chunks from {pdf_path}")
            except Exception as e:
                logging.error(f"Failed to index PDF: {e}")
        else:
            logging.warning(f"No PDF found at {pdf_path} to index.")
    else:
        logging.info("Vector store loaded successfully.")

@router.on_event("startup")
def startup_event():
    """Initializes the vector store automatically when FastAPI starts."""
    initialize_vector_store()

@router.post("/generate")
def generate_response(request: ChatRequest):
    """
    Accepts JSON with 'message' key, sends it to the LLaMA model, and returns the response.
    """
    user_message = request.message
    if not user_message:
        raise HTTPException(status_code=400, detail="Missing 'message' in request body.")

    headers = {
        "Authorization": f"Bearer {LLAMA_API_KEY}",
        "Content-Type": "application/json"
    }

    data = {
        "model": LLAMA_MODEL,
        "messages": [
            {"role": "system", "content": "You are Secure Chat Guardian — a helpful assistant."},
            {"role": "user", "content": user_message}
        ],
        "temperature": 0.7,
        "max_tokens": 512
    }

    try:
        response = requests.post(LLAMA_API_URL, headers=headers, json=data, timeout=20)
        response.raise_for_status()
        reply = response.json()

        # Extract AI message safely
        choices = reply.get("choices")
        if choices and len(choices) > 0:
            message = choices[0].get("message", {}).get("content", "")
        else:
            message = "No response generated by the model."
        return {"reply": message}

    except requests.exceptions.RequestException as e:
        raise HTTPException(status_code=500, detail=f"LLaMA API request failed: {str(e)}")

@router.post("/chat_with_pdf")
def chat_with_pdf(request: ChatRequest):
    """
    Accepts JSON with 'message' key, searches the vector store for context,
    constructs a prompt, and queries the LLaMA model.
    """
    user_message = request.message
    if not user_message:
        raise HTTPException(status_code=400, detail="Missing 'message' in request body.")

    try:
        # Search vector store for relevant chunks
        results = vector_store.search(user_message, k=3)
        context = ""
        if results:
            context = "\n---\n".join([doc for doc, score in results])

        # Build prompt using retrieved context
        system_prompt = (
            "You are Secure Chat Guardian — a helpful AI assistant. "
            "You have access to context extracted from PDF documents. "
            "Use the provided context to answer the user's question. "
            "If the answer cannot be found in the context, use your general knowledge "
            "but clearly state that the information was not found in the documents."
        )

        user_prompt = f"Context:\n{context}\n\nQuestion: {user_message}\n\nAnswer:" if context else user_message

        headers = {
            "Authorization": f"Bearer {LLAMA_API_KEY}",
            "Content-Type": "application/json"
        }

        data = {
            "model": LLAMA_MODEL,
            "messages": [
                {"role": "system", "content": system_prompt},
                {"role": "user", "content": user_prompt}
            ],
            "temperature": 0.5,
            "max_tokens": 512
        }

        response = requests.post(LLAMA_API_URL, headers=headers, json=data, timeout=20)
        response.raise_for_status()
        reply = response.json()

        choices = reply.get("choices")
        if choices and len(choices) > 0:
            message = choices[0].get("message", {}).get("content", "")
        else:
            message = "No response generated by the model."
        return {"reply": message, "sources": [doc for doc, score in results]}

    except requests.exceptions.RequestException as e:
        raise HTTPException(status_code=500, detail=f"LLaMA API request failed: {str(e)}")
    except Exception as e:
        raise HTTPException(status_code=500, detail=f"An error occurred: {str(e)}")

@router.post("/upload")
async def upload_pdf(file: UploadFile = File(...)):
    """
    Upload a PDF file, save it to backend/data, extract text, split it, and index it.
    """
    if not file.filename.endswith(".pdf"):
        raise HTTPException(status_code=400, detail="Only PDF files are supported.")
    
    upload_dir = "backend/data"
    os.makedirs(upload_dir, exist_ok=True)
    file_path = os.path.join(upload_dir, file.filename)
    
    try:
        # Save file locally
        with open(file_path, "wb") as buffer:
            shutil.copyfileobj(file.file, buffer)
            
        logging.info(f"File saved to {file_path}. Starting indexing...")
        
        # Load and split
        text = load_documents(file_path)
        if not text.strip():
            raise ValueError("The uploaded PDF has no extractable text.")
            
        chunks = split_text(text)
        
        # Add to vector store
        vector_store.add_vectors(chunks)
        logging.info(f"Successfully indexed {len(chunks)} chunks from {file.filename}")
        
        return {
            "message": f"Successfully uploaded and indexed '{file.filename}'",
            "chunks_count": len(chunks)
        }
    except Exception as e:
        # Cleanup file if failed
        if os.path.exists(file_path):
            os.remove(file_path)
        logging.error(f"Failed to process uploaded PDF: {e}")
        raise HTTPException(status_code=500, detail=f"Failed to process PDF: {str(e)}")